#!/bin/bash

./analyzer ./cover_tests/test1;echo "";
./analyzer ./cover_tests/test2;echo "";
./analyzer ./cover_tests/test3;echo "";
./analyzer ./cover_tests/test4;echo "";
./analyzer ./cover_tests/test5;echo "";
./analyzer ./cover_tests/test6;echo "";
./analyzer ./cover_tests/test7;echo "";
./analyzer ./cover_tests/test8;echo "";
./analyzer ./cover_tests/test9;echo "";
./analyzer ./cover_tests/test10;echo "";
./analyzer ./cover_tests/test11;echo "";
./analyzer ./cover_tests/test12;echo "";
./analyzer ./cover_tests/test13;echo "";
./analyzer ./cover_tests/test14;echo "";
./analyzer ./cover_tests/test15;echo "";
./analyzer ./cover_tests/test16;echo "";
./analyzer ./cover_tests/test17;echo "";
./analyzer ./cover_tests/test18;echo "";
./analyzer ./cover_tests/test19;echo "";
./analyzer ./cover_tests/test20;echo "";
./analyzer ./cover_tests/test21;echo "";
./analyzer ./cover_tests/test22;echo "";
./analyzer ./cover_tests/test23;echo "";
./analyzer ./cover_tests/test24;echo "";
./analyzer ./cover_tests/test25;echo "";
./analyzer ./cover_tests/test26;echo "";
./analyzer ./cover_tests/test27;echo "";
./analyzer ./cover_tests/test28;echo "";
./analyzer ./cover_tests/test29;echo "";
./analyzer ./cover_tests/test30;echo "";
./analyzer ./cover_tests/test31;echo "";
./analyzer ./cover_tests/test32;echo "";


