#!/bin/bash

./analyzer ./cover_tests/test1;
./analyzer ./cover_tests/test2;
./analyzer ./cover_tests/test3;
./analyzer ./cover_tests/test4;
./analyzer ./cover_tests/test5;
./analyzer ./cover_tests/test6;
./analyzer ./cover_tests/test7;
./analyzer ./cover_tests/test8;
./analyzer ./cover_tests/test9;
./analyzer ./cover_tests/test10;
./analyzer ./cover_tests/test11;
./analyzer ./cover_tests/test12;
./analyzer ./cover_tests/test13;
./analyzer ./cover_tests/test14;
./analyzer ./cover_tests/test15;
./analyzer ./cover_tests/test16;
./analyzer ./cover_tests/test17;
./analyzer ./cover_tests/test18;
./analyzer ./cover_tests/test19;
./analyzer ./cover_tests/test20;
./analyzer ./cover_tests/test21;
./analyzer ./cover_tests/test22;
./analyzer ./cover_tests/test23;
./analyzer ./cover_tests/test24;
./analyzer ./cover_tests/test25;
./analyzer ./cover_tests/test26;
./analyzer ./cover_tests/test27;
./analyzer ./cover_tests/test28;
./analyzer ./cover_tests/test29;
./analyzer ./cover_tests/test30;
./analyzer ./cover_tests/test31;
./analyzer ./cover_tests/test32;


